"""
section_parser.py — Detect markdown section headings from LlamaParse output.

LlamaParse returns PDF content as markdown, so headings look like:
    # Top-level heading
    ## Sub-heading
    ### Sub-sub-heading

This module splits a document's text into (section_title, body_text) pairs
so that downstream chunking can attach the section name as metadata.
"""

import re
from typing import List, Tuple


# ── Heading detection ─────────────────────────────────────────────────────────

# Matches markdown headings: # / ## / ###  (LlamaParse output)
_MD_HEADING = re.compile(r"^(#{1,4})\s+(.+)$", re.MULTILINE)

# Fallback: ALL-CAPS lines acting as section titles (common in Oracle docs)
_ALLCAPS_HEADING = re.compile(r"^([A-Z][A-Z\s\-/&:]{5,})$", re.MULTILINE)


def _clean(text: str) -> str:
    """Strip leading/trailing whitespace and collapse excessive blank lines."""
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def parse_sections(text: str) -> List[Tuple[str, str]]:
    """
    Split *text* into (section_heading, body) pairs.

    - Uses markdown headings first (generated by LlamaParse).
    - Falls back to ALL-CAPS line detection if no markdown headings found.
    - If neither is found the whole text is returned as one section titled
      "Document Content".

    Returns
    -------
    List of (heading: str, body: str) tuples.
    """

    sections: List[Tuple[str, str]] = []

    # ── Try markdown headings first ───────────────────────────────────────────
    heading_matches = list(_MD_HEADING.finditer(text))

    if heading_matches:
        for idx, match in enumerate(heading_matches):
            heading = match.group(2).strip()
            start   = match.end()
            end     = heading_matches[idx + 1].start() if idx + 1 < len(heading_matches) else len(text)
            body    = _clean(text[start:end])
            if body:                        # skip empty sections
                sections.append((heading, body))

        # Text before the first heading (e.g. document title intro)
        preamble = _clean(text[: heading_matches[0].start()])
        if preamble:
            sections.insert(0, ("Introduction", preamble))

        return sections

    # ── Fallback: ALL-CAPS headings (Oracle plain-text PDFs) ──────────────────
    allcaps_matches = list(_ALLCAPS_HEADING.finditer(text))

    if allcaps_matches:
        for idx, match in enumerate(allcaps_matches):
            heading = match.group(1).strip().title()        # Title-case for readability
            start   = match.end()
            end     = allcaps_matches[idx + 1].start() if idx + 1 < len(allcaps_matches) else len(text)
            body    = _clean(text[start:end])
            if body:
                sections.append((heading, body))
        return sections

    # ── No headings found — return entire text as one section ─────────────────
    return [("Document Content", _clean(text))]
